name: Reset packages
on:
  workflow_dispatch: {}
jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          persist-credentials: true

      - name: Copy old run
        run: |
          STARTTIME="$(cat runstarttime)"
          LOGDIR="logs/$(cat runstarttime)"
          mv runstarttime "$LOGDIR"/ || true
          mv alldeps.json "$LOGDIR"/ || true
          mv directdeps.json "$LOGDIR"/ || true
          mv packages.json "$LOGDIR"/ || true
          mv tobuild.txt "$LOGDIR"/ || true
          mv lists "$LOGDIR"/lists || true

      - shell: sh
        uses: "${{ secrets.CONTAINER_BASE_IMAGE }}"
        with:
          entrypoint: /bin/bash
          args: |
            .github/scripts/reset_packages.sh
