name: Reset packages
on:
  workflow_dispatch: {}
jobs:
  packages:
    runs-on: ubuntu-latest
    container: bioconductor/bioc-redis:RELEASE_3_16
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          persist-credentials: true

      - name: Copy old run
        run: |
          STARTTIME=$(cat runstarttime)
          ARCHIVEDIR="archive/$STARTTIME"
          mkdir -p "$ARCHIVEDIR"
          mv runstarttime "$ARCHIVEDIR"/
          mv alldeps.json "$ARCHIVEDIR"/
          mv packages.json "$ARCHIVEDIR"/
          mv tobuild.txt "$ARCHIVEDIR"/
          mv README.md "$ARCHIVEDIR"/
          mv lists "$ARCHIVEDIR"/lists
          mv logs "$ARCHIVEDIR"/logs

      - shell: sh
        run: |
          Rscript deps_json.R packages.json alldeps.json
          python3 -c """
          import json
          f = open('packages.json', 'r')
          pkgs = json.load(f)
          for pkg in pkgs:
              pkgs.get(pkg, []).sort()
          f.close()
          f = open('packages.json', 'w')
          f.write(json.dumps(pkgs, indent=4))
          f.close()"""
          cp packages.json alldeps.json
          echo "$(TZ=EST date '+%Y-%m-%d_%H-%M')" > runstarttime
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "Reset packages"
          git push