name: Reset packages
on:
  workflow_dispatch: {}
jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          persist-credentials: true

      - name: Copy old run
        run: |
          STARTTIME="$(cat runstarttime)"
          LOGDIR="logs/$(cat runstarttime)"
          mv runstarttime "$LOGDIR"/ || true
          mv alldeps.json "$LOGDIR"/ || true
          mv directdeps.json "$LOGDIR"/ || true
          mv packages.json "$LOGDIR"/ || true
          mv tobuild.txt "$LOGDIR"/ || true
          mv lists "$LOGDIR"/lists || true

      - shell: sh
        uses: "${{ secrets.CONTAINER_BASE_IMAGE }}"
        run: |
          Rscript .github/scripts/deps_json.R packages.json directdeps.json
          python3 -c """
          import json
          f = open('packages.json', 'r')
          pkgs = json.load(f)
          for pkg in pkgs:
              pkgs.get(pkg, []).sort()
          f.close()
          f = open('packages.json', 'w')
          f.write(json.dumps(pkgs, indent=4))
          f.close()"""
          cp packages.json alldeps.json
          echo "$(TZ=EST date '+%Y-%m-%d-%H-%M')" > runstarttime
          bash .github/scripts/set_container_name.sh
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "Reset packages"
          git push
